name = "Discord"
uuid = "e67e5439-1494-44b2-b9ab-d191a16377ec"
authors = ["Chris de Graaf <me@cdg.dev> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SuperEnum = "5c958174-e7d9-5990-9618-4567de4ba542"

[compat]
HTTP = "0.8"
JSON3 = "1"
Parameters = "0.12"
SuperEnum = "0.1"
julia = "1"

[extras]
BrokenRecord = "bdd55f5b-6e67-4da1-a080-6086e55655a0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BrokenRecord", "Test"]
